---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    pkigen_output_path: "/tmp"
    pkigen_ca_common_name: "*.willbrid.com"
    pkigen_ca_secret_passphrase: "test@test"
    pkigen_cert_file_name: "willbrid.com"
    pkigen_cert_common_name: "*.willbrid.com"
    pkigen_cert_organization_name: "willbrid"
    pkigen_cert_organizational_unit_name: "willbrid"
    pkigen_cert_email_address: "admin@willbrid.com"
    pkigen_cert_country_name: "FR"
    pkigen_cert_valid_for: "+365d"
    pkigen_cert_valid_since: "-1d"
    pkigen_cert_alt_names:
      - "willbrid.com"
      - "*.willbrid.com"

  tasks:
    - name: Include willbrid.pki_generator
      ansible.builtin.include_role:
        name: "willbrid.pki_generator"
